### ISSUE TITLE
LSOA outputs: multiple versions of same LSOA and not matching TTWAs correctly

### ISSUE THREAD

**Issue by DanOlner** [life-at-the-frontier/detect-uk-frontiers#1]
Hi Meng Le - there's code in the [frontiers dashboard page](https://github.com/DanOlner/ShinyMapEssentials/blob/241894da3c2693279cfec4e42b6d5fcc879cb284/othercode/dataprep.R#L69) that shows this issue. The LSOAs coming out from here - there are repeats of LSOAs where a single LSOA matched with multiple TTWAs (up to 5 repeats), and a number of them where there's no TTWA match so just NA. I've looking on the map, and the NAs are (AFAIK) all in the "K" category of TTWAs - i.e. the ones that overlap two countries.

The code above hacks a fix for that - it keeps only individual LSOAs and then re-assigns the TTWA lookup using a different TTWA file. The TTWA file I've used is slightly less generalised, so it matches the lines of the LSOAs we're using. You can find a zip of that [here](https://www.dropbox.com/s/07aj875v6mnnwfy/greatBritainTTWAs.zip?dl=1). 

Hope that might help identify what's going on at this end.

**Comment by MengLeZhang** [comment]
I figured this problem comes from using spatial joins and my haphazard early trials. Will use official ons lsoa to ttwa lookup going forward [here](https://geoportal.statistics.gov.uk/datasets/ons::lower-layer-super-output-area-2011-to-travel-to-work-area-december-2011-lookup-in-the-united-kingdom-1/explore).
